// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"

	"github.com/gin-gonic/gin"
	"github.com/redis/go-redis/v9"
	"go.mongodb.org/mongo-driver/mongo"

	"social-network-system/pkg/database"
	"social-network-system/pkg/jwtutil"
	"social-network-system/pkg/kafka"
	"social-network-system/services/chat/config"
	deliveryhttp "social-network-system/services/chat/internal/delivery/http"
	"social-network-system/services/chat/internal/delivery/ws"
	mongorepo "social-network-system/services/chat/internal/repository/mongodb"
	redisrepo "social-network-system/services/chat/internal/repository/redis"
	"social-network-system/services/chat/internal/usecase"
)

// Injectors from wire.go:

// InitializeApp initializes all dependencies and constructs the App.
func InitializeApp(cfg *config.Config) (*App, func(), error) {
	engine := provideEngine()
	client, cleanup, err := provideMongoClient(cfg)
	if err != nil {
		return nil, nil, err
	}
	redisClient, cleanup2, err := provideRedisClient(cfg)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	producer, cleanup3 := provideKafkaProducer(cfg)
	mongoDatabase := provideMongoDatabase(client, cfg)
	chatRepository := mongorepo.NewChatRepository(mongoDatabase)
	presenceRepository := redisrepo.NewPresenceRepository(redisClient)
	tokenManager := provideTokenManager(cfg)
	chatUseCase := usecase.NewChatUseCase(chatRepository, producer)
	chatHandler := deliveryhttp.NewChatHandler(chatUseCase)
	wsHandler := ws.NewWSHandler(cfg, chatUseCase, presenceRepository, tokenManager, redisClient)
	app := &App{
		Config:       cfg,
		Engine:       engine,
		MongoClient:  client,
		RedisClient:  redisClient,
		ChatHandler:  chatHandler,
		WSHandler:    wsHandler,
		TokenManager: tokenManager,
	}
	return app, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

func provideMongoClient(cfg *config.Config) (*mongo.Client, func(), error) {
	client, _, err := database.ConnectMongoDB(context.Background(), cfg.MongoURI, cfg.MongoDBName)
	cleanup := func() {
		if client != nil {
			_ = client.Disconnect(context.Background())
		}
	}
	return client, cleanup, err
}

func provideMongoDatabase(client *mongo.Client, cfg *config.Config) *mongo.Database {
	return client.Database(cfg.MongoDBName)
}

func provideRedisClient(cfg *config.Config) (*redis.Client, func(), error) {
	client, err := database.ConnectRedis(context.Background(), cfg.RedisURI, cfg.RedisPassword)
	cleanup := func() {
		if client != nil {
			_ = client.Close()
		}
	}
	return client, cleanup, err
}

func provideTokenManager(cfg *config.Config) jwtutil.TokenManager {
	return jwtutil.NewJWTManager(cfg.JWTSecret)
}

func provideEngine() *gin.Engine {
	return gin.Default()
}

func provideKafkaProducer(cfg *config.Config) (kafka.Producer, func()) {
	producer := kafka.NewProducer(cfg.KafkaBrokers, cfg.KafkaTopicChatIncoming)
	cleanup := func() {
		_ = producer.Close()
	}
	return producer, cleanup
}
