// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/gin-gonic/gin"
	redis2 "github.com/redis/go-redis/v9"
	"go.mongodb.org/mongo-driver/mongo"
	"social-network-system/pkg/database"
	"social-network-system/pkg/hash"
	"social-network-system/pkg/jwtutil"
	"social-network-system/services/auth/config"
	"social-network-system/services/auth/internal/delivery/http"
	"social-network-system/services/auth/internal/repository/mongodb"
	"social-network-system/services/auth/internal/repository/redis"
	"social-network-system/services/auth/internal/usecase"
)

// Injectors from wire.go:

// InitializeApp initializes all dependencies and constructs the App.
func InitializeApp(cfg *config.Config) (*App, func(), error) {
	engine := provideEngine()
	client, cleanup, err := provideMongoClient(cfg)
	if err != nil {
		return nil, nil, err
	}
	redisClient, cleanup2, err := provideRedisClient(cfg)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	database := provideMongoDatabase(client, cfg)
	userRepository := mongodb.NewUserRepository(database)
	tokenRepository := redis.NewTokenRepository(redisClient)
	passwordHasher := providePasswordHasher()
	tokenManager := provideTokenManager(cfg)
	authUseCase := usecase.NewAuthUseCase(userRepository, tokenRepository, passwordHasher, tokenManager)
	authHandler := http.NewAuthHandler(authUseCase)
	app := &App{
		Config:       cfg,
		Engine:       engine,
		MongoClient:  client,
		RedisClient:  redisClient,
		AuthHandler:  authHandler,
		TokenManager: tokenManager,
	}
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

func provideMongoClient(cfg *config.Config) (*mongo.Client, func(), error) {
	client, _, err := database.ConnectMongoDB(context.Background(), cfg.MongoURI, cfg.MongoDBName)
	cleanup := func() {
		if client != nil {
			_ = client.Disconnect(context.Background())
		}
	}
	return client, cleanup, err
}

func provideMongoDatabase(client *mongo.Client, cfg *config.Config) *mongo.Database {
	return client.Database(cfg.MongoDBName)
}

func provideRedisClient(cfg *config.Config) (*redis2.Client, func(), error) {
	client, err := database.ConnectRedis(context.Background(), cfg.RedisURI, cfg.RedisPassword)
	cleanup := func() {
		if client != nil {
			_ = client.Close()
		}
	}
	return client, cleanup, err
}

func provideTokenManager(cfg *config.Config) jwtutil.TokenManager {
	return jwtutil.NewJWTManager(cfg.JWTSecret)
}

func providePasswordHasher() hash.PasswordHasher {
	return hash.NewBcryptHasher(0)
}

func provideEngine() *gin.Engine {
	return gin.Default()
}
