// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/gin-gonic/gin"
	"go.mongodb.org/mongo-driver/mongo"
	"social-network-system/pkg/database"
	"social-network-system/pkg/jwtutil"
	"social-network-system/services/post/config"
	"social-network-system/services/post/internal/delivery/http"
	"social-network-system/services/post/internal/repository/mongodb"
	"social-network-system/services/post/internal/usecase"
)

// Injectors from wire.go:

// InitializeApp initializes all dependencies and constructs the App.
func InitializeApp(cfg *config.Config) (*App, func(), error) {
	engine := provideEngine()
	client, cleanup, err := provideMongoClient(cfg)
	if err != nil {
		return nil, nil, err
	}
	mongoDatabase := provideMongoDatabase(client, cfg)
	postRepository := mongodb.NewPostRepository(mongoDatabase)
	followRepository := mongodb.NewFollowRepository(mongoDatabase)
	tokenManager := provideTokenManager(cfg)
	postUseCase := usecase.NewPostUseCase(postRepository)
	followUseCase := usecase.NewFollowUseCase(followRepository)
	postHandler := http.NewPostHandler(postUseCase)
	followHandler := http.NewFollowHandler(followUseCase)
	app := &App{
		Config:        cfg,
		Engine:        engine,
		MongoClient:   client,
		PostHandler:   postHandler,
		FollowHandler: followHandler,
		TokenManager:  tokenManager,
	}
	return app, func() {
		cleanup()
	}, nil
}

// wire.go:

func provideMongoClient(cfg *config.Config) (*mongo.Client, func(), error) {
	client, _, err := database.ConnectMongoDB(context.Background(), cfg.MongoURI, cfg.MongoDBName)
	cleanup := func() {
		if client != nil {
			_ = client.Disconnect(context.Background())
		}
	}
	return client, cleanup, err
}

func provideMongoDatabase(client *mongo.Client, cfg *config.Config) *mongo.Database {
	return client.Database(cfg.MongoDBName)
}

func provideTokenManager(cfg *config.Config) jwtutil.TokenManager {
	return jwtutil.NewJWTManager(cfg.JWTSecret)
}

func provideEngine() *gin.Engine {
	return gin.Default()
}
